import { useEffect, useRef, useState } from 'react'
import { Heart, MessageCircle, Share2, Volume2, VolumeX } from 'lucide-react'
import { Link } from 'react-router-dom'
import { socialClient } from '../../lib/socialClient'

const relative=value=>{const sec=Math.max(1,(Date.now()-new Date(value))/1000);if(sec<60)return 'just now';if(sec<3600)return `${Math.floor(sec/60)}m`;if(sec<86400)return `${Math.floor(sec/3600)}h`;return `${Math.floor(sec/86400)}d`}
export default function PostCard({initial,user}){
 const [post,setPost]=useState(initial),[comments,setComments]=useState(null),[body,setBody]=useState(''),[muted,setMuted]=useState(true);const video=useRef()
 const liked=(post.post_likes||[]).some(x=>x.user_id===user?.id)
 useEffect(()=>{if(!video.current)return;const ob=new IntersectionObserver(([x])=>x.isIntersecting?video.current.play().catch(()=>{}):video.current.pause(),{threshold:.65});ob.observe(video.current);return()=>ob.disconnect()},[])
 const like=async()=>{if(!user)return;const before=post;setPost({...post,like_count:Math.max(0,post.like_count+(liked?-1:1)),post_likes:liked?post.post_likes.filter(x=>x.user_id!==user.id):[...(post.post_likes||[]),{user_id:user.id}]});const r=await socialClient.toggleLike(before,user.id);if(r.error)setPost(before)}
 const openComments=async()=>{if(comments){setComments(null);return}const r=await socialClient.comments(post.id);setComments(r.data||[])}
 const add=async e=>{e.preventDefault();if(!body.trim())return;const r=await socialClient.addComment(post.id,body.trim());if(!r.error){setComments([...(comments||[]),r.data]);setBody('');setPost({...post,comment_count:post.comment_count+1})}}
 const author=post.profiles||{}, artist=post.artists||{};return <article className="post-card"><header><Link to={`/profile/${author.username}`}><img src={author.avatar_url||post.post_media?.[0]?.url} alt=""/><span><strong>{author.display_name||artist.name}</strong><small>{artist.category}{author.city||artist.city?` · ${author.city||artist.city}`:''} · {relative(post.created_at)}</small></span></Link>{user&&user.id!==post.author_id&&<button className="follow-quiet" onClick={()=>socialClient.toggleFollow(post.author_id,user.id)}>Follow</button>}</header><p className="post-caption">{post.caption}</p><div className="post-media">{post.media_type==='video'?<><video ref={video} src={post.post_media?.[0]?.url} muted={muted} loop playsInline/><button onClick={()=>setMuted(!muted)} aria-label={muted?'Unmute video':'Mute video'}>{muted?<VolumeX/>:<Volume2/>}</button></>:post.post_media?.map(m=><img key={m.id} src={m.url} alt={post.caption||'Artist performance'}/>)}</div><div className="post-actions"><button className={liked?'active':''} onClick={like} aria-label="Like post"><Heart fill={liked?'currentColor':'none'}/> {post.like_count}</button><button onClick={openComments}><MessageCircle/> {post.comment_count}</button><button onClick={()=>navigator.clipboard?.writeText(`${location.origin}/discover?post=${post.id}`)}><Share2/> {post.share_count}</button></div>{comments&&<section className="comment-thread"><form onSubmit={add}><input maxLength="500" value={body} onChange={e=>setBody(e.target.value)} placeholder="Add a comment"/><button>Post</button></form>{comments.length?comments.map(c=><p key={c.id}><strong>{c.profiles?.display_name||'Evntra user'}</strong> {c.body}</p>):<p>No comments yet.</p>}</section>}</article>
}
