import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Search, SlidersHorizontal, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import ArtistCard from '../components/ArtistCard'
import { dataClient } from '../lib/dataClient'
import { categories } from '../lib/categories'

export default function Home({user}) {
  const [artists,setArtists]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[drawer,setDrawer]=useState(false),[params,setParams]=useSearchParams()
  const [draft,setDraft]=useState(params.get('q')||'')
  const selected=params.getAll('category'), city=params.get('city')||'', minRating=Number(params.get('min_rating')||0), minPrice=params.get('min_price')||'', maxPrice=params.get('max_price')||'', sort=params.get('sort')||'relevance'
  const update=(key,value,{multi=false}={})=>{const next=new URLSearchParams(params);if(multi){const values=next.getAll(key);next.delete(key);(values.includes(value)?values.filter(x=>x!==value):[...values,value]).forEach(x=>next.append(key,x))}else if(value)next.set(key,value);else next.delete(key);setParams(next)}
  useEffect(()=>{const timer=setTimeout(()=>update('q',draft),300);return()=>clearTimeout(timer)},[draft])
  useEffect(()=>{dataClient.listArtists().then(r=>{if(r.error)setError(r.error.message);else setArtists(r.data||[]);setLoading(false)})},[])
  const filtered=useMemo(()=>{const q=(params.get('q')||'').toLowerCase();const rows=artists.filter(a=>(!selected.length||[a.category,...(a.tags || [])].some(c=>selected.includes(c)))&&(!city||a.city?.toLowerCase().includes(city.toLowerCase()))&&(!q||`${a.name} ${a.category} ${(a.tags || []).join(' ')} ${a.city} ${a.bio}`.toLowerCase().includes(q))&&Number(a.rating||0)>=minRating&&(!minPrice||Number(a.price_per_event)>=Number(minPrice))&&(!maxPrice||Number(a.price_per_event)<=Number(maxPrice)));return rows.sort((a,b)=>sort==='rating'?b.rating-a.rating:sort==='price_low'?a.price_per_event-b.price_per_event:sort==='price_high'?b.price_per_event-a.price_per_event:sort==='newest'?new Date(b.created_at)-new Date(a.created_at):0)},[artists,params.toString()])
  const clear=()=>{setDraft('');setParams({})}
  const filters=<div className="filter-panel"><div className="filter-title"><strong>Filters</strong><button onClick={()=>setDrawer(false)} aria-label="Close filters"><X/></button></div><fieldset><legend>Categories</legend>{categories.map(c=><label key={c}><input type="checkbox" checked={selected.includes(c)} onChange={()=>update('category',c,{multi:true})}/>{c}</label>)}</fieldset><label>City<input value={city} onChange={e=>update('city',e.target.value)} placeholder="Any city"/></label><div className="field-row"><label>Min price<input type="number" value={minPrice} onChange={e=>update('min_price',e.target.value)} min="0"/></label><label>Max price<input type="number" value={maxPrice} onChange={e=>update('max_price',e.target.value)} min="0"/></label></div><label>Minimum rating<select value={minRating} onChange={e=>update('min_rating',e.target.value)}><option value="0">Any</option><option value="4">4+</option><option value="4.5">4.5+</option></select></label><button className="button outline" onClick={clear}>Clear filters</button></div>
  return <><section className="hero"><div className="paper-shape paper-one"/><div className="paper-shape paper-two"/><div className="paper-shape paper-three"/><div className="hero-glow"/><div className="eyebrow">Find your perfect performer</div><h1>Great events start<br/><em>with great artists.</em></h1><p>Search, compare, and request your date in minutes.</p><div className="search-box"><Search size={20}/><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Name, category, city, or bio" aria-label="Search artists"/><button onClick={()=>document.getElementById('artist-results')?.scrollIntoView({behavior:'smooth'})}>Search <ArrowRight size={17}/></button></div></section><section className="search-results page" id="artist-results"><button className="mobile-filter" onClick={()=>setDrawer(true)}><SlidersHorizontal/> Filters</button><aside className={drawer?'open':''}>{filters}</aside><div className="results-main"><div className="listing-heading"><div><p className="kicker">Marketplace</p><h2>Artists for your event</h2><p>{loading?'Finding artists…':`${filtered.length} results`}</p></div><label>Sort<select value={sort} onChange={e=>update('sort',e.target.value)}><option value="relevance">Relevance</option><option value="rating">Rating</option><option value="price_low">Price: low to high</option><option value="price_high">Price: high to low</option><option value="newest">Newest</option></select></label></div>{loading?<div className="loading-grid">{[1,2,3].map(x=><div className="skeleton" key={x}/>)}</div>:error?<div className="notice"><h3>Artists could not load</h3><p>{error}</p></div>:filtered.length?<div className="artist-grid">{filtered.map(a=><ArtistCard key={a.id} artist={a} user={user}/>)}</div>:<div className="empty bordered"><h3>No artists match those filters</h3><p>Try widening the price, rating, or location.</p><button className="button" onClick={clear}>Clear filters</button></div>}</div></section></>
}
